### ISSUE TITLE
grabbed window moves to a new desktop

### ISSUE THREAD

**Issue by kupiqu** [Ubiquitine/MACsimize6#9]
When I grab a window to tile, it automatically moves to a new desktop, which is annoying.

I realized that I previously had the feature "Move window to the last virtual desktop" enabled, however disabling the feature has no effect.

**Comment by Ubiquitine** [comment]
What do you mean by "grab a window to tile"?
Do you mean a quick tile (drag window with Shift pressed)? In that case I cannot reproduce it. I tried all kind of tiles configured and nothing triggers such behavior.
Unless you grab window and drag it to the top, which triggers window to be maximized. In that case this is an expected behavior.

**Comment by kupiqu** [comment]
I realized this is an interaction in the script with the kzones kwin script. When both are enabled, dragging the window triggers MACsimize so the window moves to a new desktop. This doesn't happen if any of the two scripts are disabled.

**Comment by kupiqu** [comment]
This is the other script: https://github.com/gerritdevriese/kzones

**Comment by Ubiquitine** [comment]
From quick look at that scrip I see that it does maximize windows at some point during the zone assignment. That explains why my script triggers new desktop creation and moving the window there. After all this is what it supposed to do. I guess the only way for both scripts to work together is to disable new desktop creation for maximized windows in the script config and only do so to fullscreen.
I'm closing this report as having multiple scripts enabled that change window and desktops behavior at the same time is not supported.

**Comment by kupiqu** [comment]
I understand, thank you. I opened an issue in kzones for the case something can be done about this there

**Comment by gerritdevriese** [comment]
Hi @Ubiquitine, I think the KZones overlay, which opens when moving a window, is triggering your script.

If you add a few more checks to your script I think this should solve the KZones issue and also not require as much default exclusions like #7.

For example: The KZones overlay could be excluded by checking `client.skipTaskbar` and splash screens `client.splash`. Also `client.normalWindow` is a good one to have.

[Here](https://develop.kde.org/docs/plasma/kwin/api/#read-only-properties-4) are all available client properties.

**Comment by Ubiquitine** [comment]
Script already checks for `client.normalWindow` . Let me check if adding checks for `skipTaskbar ` and splash might fix the issue.
Also I tested MACsimize6 with KZones enabled together and couldn't reproduce the issue.

**Comment by gerritdevriese** [comment]
> Also I tested MACsimize6 with KZones enabled together and couldn't reproduce the issue.

I just tried too, it only happens on X11, on Wayland it's fine.

**Comment by Ubiquitine** [comment]
Just for legacy X11 I added some checks for splash and skipTaskbar. 
Can you test it on X11? 
Above MR shows the changes done for content/code/main.js file. The script is located in your home directory in ~/.local/share/kwin/scripts/macsimize6 . Just edit the file here and restart KWin. Or logout and login into X11 session...

**Comment by kupiqu** [comment]
I can confirm this:

> Weirdly that didn't solve it, but adding `'kwin'` to `systemSkippedWindows` did.

Adding `'kwin_x11'` doesn't fix the issue though, only  `'kwin'`

**Comment by Ubiquitine** [comment]
Could you test this for a while to see if adding kwin class doesn't break anything else? It does seem reasonable, though.
